# Generated by Django 5.1.3 on 2024-11-30 12:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.RemoveField(
            model_name='localizeaccommodation',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='parent_id',
        ),
        migrations.DeleteModel(
            name='Accommodation',
        ),
        migrations.DeleteModel(
            name='LocalizeAccommodation',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
