# Generated by Django 5.1.3 on 2024-12-02 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_accommodation_localizeaccommodation_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodation',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='accommodation',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='localizeaccommodation',
            name='property_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='accommodation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='localizeaccommodation',
            name='property',
            field=models.ForeignKey(default='ACM001', on_delete=django.db.models.deletion.CASCADE, related_name='localized_accommodations', to='inventory.accommodation'),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.location'),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='localizeaccommodation',
            name='policy',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default='Unknown City', max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('continent', 'Continent'), ('country', 'Country'), ('state', 'State'), ('city', 'City')], max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='state_abbr',
            field=models.CharField(default='XX', max_length=3),
        ),
    ]
